### PR TITLE
Add initial tvOS support

### PR DESCRIPTION
**Pull request by SiarheiFedartsou**

### CODE REVIEW

**Comment by amichnia** [comment]
@SiarheiFedartsou Hi - thanks for your pr. We'll get to it as soon as possible :) Meanwhile - why don't you join our [slack](https://join.slack.com/t/swiftymocky/shared_invite/enQtMjc0NzI5ODU3NTcxLTdmN2Q0NzQ3OWFmYTZlZmZkYTI3M2VmNzAzZDIzNWUwYjVhOTlmYWFiYzc2OGZkMzBkN2RkMmQ3NzQyMmIyNDU) :)

**Comment by amichnia** [comment]
@SiarheiFedartsou - I submitted pr to your branch. Updated structure and added travis/fastlane stuff.

Main idea is to come up with convention for next platforms while keeping some consistent structure of project. Let me know what you think.

**Comment by SiarheiFedartsou** [comment]
@amichnia Hm, do we really need separate test suite for tvOS? I think there will be no any difference  between iOS and tvOS from this perspective. And we can keep the same tests for all platforms(but add files to both iOS and tvOS targets).

**Comment by amichnia** [comment]
@SiarheiFedartsou - you are right, maintaining two sets of exactly same tests does not seems like a good idea. Could we place shared tests in same folder, like "Shared" for protocols? I would really like to have folder structure obvious for someone, who downloads example project (shared + platform specific tests if any).

The only thing that bothered me is modules naming, cause all tests imports `@testsable Mocks_Example_<platform>`. Anyway - I'll update my pr, will see if I can update that.

**Comment by amichnia** [comment]
@SiarheiFedartsou - after some discussion we decided to leave that topic (rearrangement of project structure) for now. 

So, sorry for waiting (there were some hot fixes pending), and thanks again a lot for your contribution! Merging.

**Pull request merged**
