### PR TITLE
Actualize Yams dependency version

### PR DESCRIPTION
**Pull request by navartis**
I carefully read https://github.com/MakeAWishFoundation/SwiftyMocky/blob/master/CONTRIBUTING.md

But the `develop` branch extremely outdated.
So I had to use `master` branch as target for this PR.

### CODE REVIEW

**Comment by navartis** [comment]
@g-amichnia 🙏

**Comment by navartis** [comment]
Bleyat

**Comment by spaluchiewicz** [comment]
@tercteberc, @navartis is this PR still valid or YAMS should be bumped?

**Review by spaluchiewicz — APPROVED** [review]
Looks good.

**Comment by navartis** [comment]
@spaluchiewicz Sebastian, now a time actual this PR is valid and currently actual.
While waiting for review, the new version of Yams was released)
I upgraded the version Yams up to current stable release version, run tests - OK.

Kindly ask you for review.
Have a nice day;)

**Comment by spaluchiewicz** [comment]
@navartis 

```bash
Run maxim-lobanov/setup-xcode@v1
Switching Xcode to version '13.[4](https://github.com/MakeAWishFoundation/SwiftyMocky/runs/7748848946?check_suite_focus=true#step:3:5).1'...
Available versions:
┌─────────┬──────────┬─────────────┬─────────────┬────────┬──────────────────────────────────┐
│ (index) │ version  │ buildNumber │ releaseType │ stable │               path               │
├─────────┼──────────┼─────────────┼─────────────┼────────┼──────────────────────────────────┤
│    0    │ '13.2.1' │  '13C100'   │    'GM'     │  true  │ '/Applications/Xcode_13.2.1.app' │
│    1    │ '13.1.0' │ '13A1030d'  │    'GM'     │  true  │  '/Applications/Xcode_13.1.app'  │
│    2    │ '13.0.0' │  '13A233'   │    'GM'     │  true  │  '/Applications/Xcode_13.0.app'  │
│    3    │ '12.[5](https://github.com/MakeAWishFoundation/SwiftyMocky/runs/7748848946?check_suite_focus=true#step:3:6).1' │  '12E50[7](https://github.com/MakeAWishFoundation/SwiftyMocky/runs/7748848946?check_suite_focus=true#step:3:8)'   │    'GM'     │  true  │ '/Applications/Xcode_12.5.1.app' │
│    4    │ '12.4.0' │   '12D4e'   │    'GM'     │  true  │  '/Applications/Xcode_12.4.app'  │
│    5    │ '11.7.0' │  '11E[8](https://github.com/MakeAWishFoundation/SwiftyMocky/runs/7748848946?check_suite_focus=true#step:3:9)01a'  │    'GM'     │  true  │  '/Applications/Xcode_[11](https://github.com/MakeAWishFoundation/SwiftyMocky/runs/7748848946?check_suite_focus=true#step:3:12).7.app'  │
└─────────┴──────────┴─────────────┴─────────────┴────────┴──────────────────────────────────┘
Error: Could not find Xcode version that satisfied version spec: '[13](https://github.com/MakeAWishFoundation/SwiftyMocky/runs/7748848946?check_suite_focus=true#step:3:14).4.1'
```

**Pull request merged**
