### PR TITLE
Add protocol compositions

### PR DESCRIPTION
**Pull request by erneestoc**
Add ability to generate mocks for protocol compositions. I've been using a router approach similar to what is described in this [blog post](https://medium.com/rosberryapps/the-flexible-routing-approach-in-an-ios-app-eb4b05aa7f52) which uses protocol compositions, and I've been generating mocks manually. Having SwiftyMocky generate mocks for protocolCompositions would be a huge time saver. 🙏🏻 

All tests passing ✅
Referencing: https://github.com/MakeAWishFoundation/SwiftyMocky/issues/275

### CODE REVIEW

**Comment by erneestoc** [comment]
What do you think @amichnia ? :)

**Comment by g-amichnia** [comment]
@erneestoc I am super positive! Thanks for the change, it is great.

Just one remark before we can merge it. (I think we need some doc for that btw., since it happens very often.)

Because we have two pods here at the moment (SwiftyMocky and SwiftyPrototyping), and because editing one big template was such a problem, we once tried to split template into reasonable chunks. That works well enough for us (but it still is irritating), but all other contributors struggle with that :)

Anyway, the files you need to change reside in `Templates/` dir, nit `Sources/`. That would be:

- `Templates/Main.swifttemplate`
- `Templates/AllTypes.swiftemplate` // it will be used by CLI, for auto resolving imports, it can use your change too!

After that, we have a `Rakefile` in main project dir, so you run `rake update` and that should combine all the parts from `Templates` and generate valid `Mock.swifttemplate` and `Prototype.swiftemplate` in sources.

Sorry for inconvenience, I will push this commit as soon as I can.

**Review by g-amichnia — CHANGES_REQUESTED** [review]
Review: requested changes, move change to right files in `Tempaltes` and run `rake update`.

**Comment by erneestoc** [comment]
@g-amichnia change was actually ready on `Templates/Main.swifttemplate` and was updated on the other files by using the `rake update` command :) it was a little confusing to figure that out though, would be nice to have a guide for contributors..

I added the change to `Templates/AllTypes.swiftemplate`, added a small change on README and guides/Overview, ran `rake docs`.

One small suggestion would be to use a `Gemfile` so that cocoapods and jazzy versions are aligned on contributors machines. 🧐

**Review by g-amichnia — APPROVED** [review]

**Pull request merged**
